---
- hosts: localhost
  gather_facts: false
  vars:
    aws_access_key: "your-aws-access-key"
    aws_secret_key: "your-aws-secret-key"
    aws_region: "ap-south-1"
  tasks:
    - name: Fetch EC2 instances
      ec2_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "ap-south-1"
      register: ec2_info

    - name: Convert to Excel format
      community.general.json2xlsx:
        data: "{{ ec2_info.instances }}"
        sheet_name: "EC2 Instances"
        path: "/tmp/tower/file.xlsx"
