---
- name: Generate AWS inventory
  hosts: all
  gather_facts: False


  tasks:
    - name: Generate inventory
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "*"
      register: ec2_instances

    - name: Save output to CSV
      copy:
        content: "{{ ec2_instances.instances | to_nice_json }}"
        dest: inventory.csv
