---
- name: configure a simple apache server
  hosts: ec2-15-206-190-213.ap-south-1.compute.amazonaws.com
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: create index.html file
      copy:
        content: "Sample Apache Server."
        dest: /var/www/html/index.html
