---
- name: inventory
  hosts: 3.110.140.151
  tasks:
  - name: Info for EC2 instances
    ec2_instance_info:
      region: ap-south-1
    register: out
  - name: Display the info for EC2
    template:
      src: generate_csv2.j2
      dest: ec2_instance_info.csv
  - name: Download CSV file
    fetch:
      src: /tmp/ec2_instance_info.csv
      dest: C:\Users\leena\Desktop\Inventory\ec2_instance_info.csv
      flat: yes
      fail_on_missing: yes
