---
- name: inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Info for EC2 instances
    ec2_instance_info:
      region: ap-south-1
    register: out
  - name: Display the info for EC2
    template:
      src: generate_csv2.j2
      dest: /tmp/ec2_instance_info.csv
  - name: Download CSV file
    winrm_copy:
      src: /tmp/ec2_instance_info.csv
      dest: C:\Users\leena\Desktop\Inventory\ec2_instance_info.csv
      winrm_username: "administrator"
      winrm_password: "250683"
      winrm_transport: "ntlm"
