---
- name: inventory
  hosts: localhost
  connection: local
  gather_facts: False
  become: true
  become_method: sudo
  tasks:
  - name: Info for EC2 instances
    ec2_instance_info:
      region: ap-south-1
    register: out
  - name: Display the info for EC2
    template:
      src: generate_csv2.j2
      dest: ec2_instance_info.csv
   - name: Update permission for file
     file:
      path: ec2_instance_info.csv
      mode: '0777'
  - name: Download CSV file
    win_copy:
      src: ec2_instance_info.csv
      dest: C:\Users\leena\Desktop\Inventory\ec2_instance_info.csv
