---
- name: inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Info for EC2 instances
    ec2_instance_info:
      region: ap-south-1
    register: out
  - name: Display the info for EC2
    template:
      src: /var/lib/awx/venv/ansible/generate_csv2.j2
      dest: /var/lib/awx/venv/ansible/ec2_instance_info.csv
  
