---
- hosts: servers
  become: true
  vars:
    os_version: "new-os-version"
  tasks:
    - name: Pre-upgrade checks
      shell: "/path/to/pre-upgrade-check-script.sh"
      register: upgrade_check_result
      changed_when: false

    - name: Check if upgrade is feasible
      fail:
        msg: "Upgrade is not feasible. Check failed: {{ upgrade_check_result.stdout }}"
      when: upgrade_check_result.stdout != "All checks passed."

    - name: Perform in-place OS upgrade
      shell: "/path/to/os-upgrade-script.sh {{ os_version }}"
      async: 300
      poll: 10
