---
- name: Start EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Gather facts about EC2 instance
      ec2_instance_info: 
        instance_ids: "{{ instance_ids }}"
      register: ec2_info
    - name: Stop EC2 instance
      ec2:
        instance_ids: "{{ instance_ids }}"
        state: running
