---
- name: Stop EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Gather facts about EC2 instance
      ec2_instance_info: 
        instance_ids: "{{ instance_ids }}"
        region: ap-south-1
      register: ec2_info
    - name: Stop EC2 instance
      ec2:
        instance_ids: "{{ instance_ids }}"
        state: stopped
        region: ap-south-1
